//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverParse.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OverParse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Always on top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-End Encounters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoEnd {
            get {
                return ResourceManager.GetString("AutoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-hide window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoHide {
            get {
                return ResourceManager.GetString("AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackOp {
            get {
                return ResourceManager.GetString("BackOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse is a 3rd-party tool that breaks PSO2&apos;s Terms and Conditions.
        ///SEGA has confirmed in an official announcement that accounts found using parsing tools may be banned.
        ///If account safety is your first priority, do NOT use OverParse. You use this tool entirely at your own risk.
        ///Would you like to continue with setup? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BanWarning {
            get {
                return ResourceManager.GetString("BanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not save data to clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cantclip {
            get {
                return ResourceManager.GetString("Cantclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change .csv update interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Changeinv {
            get {
                return ResourceManager.GetString("Changeinv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable GPU Rendering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUDraw {
            get {
                return ResourceManager.GetString("CPUDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard Encounter (No Log) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiscardEncounter {
            get {
                return ResourceManager.GetString("DiscardEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup is complete. Please restart PSO2 if it is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Donedll {
            get {
                return ResourceManager.GetString("Donedll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change DPS Display Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DPSFormat {
            get {
                return ResourceManager.GetString("DPSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Encounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndEncounter {
            get {
                return ResourceManager.GetString("EndEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured during setup. Please check that PSO2 is not running and that OverParse has read/write permissions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Errordll {
            get {
                return ResourceManager.GetString("Errordll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide A.I.S. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideAIS {
            get {
                return ResourceManager.GetString("HideAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Attack Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideAtk {
            get {
                return ResourceManager.GetString("HideAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Critical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideCri {
            get {
                return ResourceManager.GetString("HideCri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Dark Blast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideDB {
            get {
                return ResourceManager.GetString("HideDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide JA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideJA {
            get {
                return ResourceManager.GetString("HideJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Laconium Sword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideLsw {
            get {
                return ResourceManager.GetString("HideLsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anonymize Names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideName {
            get {
                return ResourceManager.GetString("HideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Enemy/NPCs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideNPC {
            get {
                return ResourceManager.GetString("HideNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Players に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HidePlayer {
            get {
                return ResourceManager.GetString("HidePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Photon Weapons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HidePwp {
            get {
                return ResourceManager.GetString("HidePwp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Rideroid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideRide {
            get {
                return ResourceManager.GetString("HideRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higlight Self に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dll plugin install now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installdll {
            get {
                return ResourceManager.GetString("Installdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low Priority Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LowResources {
            get {
                return ResourceManager.GetString("LowResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse requires PSO2DamageDump.dll in order to recieve damage logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Needdll {
            get {
                return ResourceManager.GetString("Needdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This release of OverParse includes a new version of the parsing plugin. Would you like to update now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Newdll {
            get {
                return ResourceManager.GetString("Newdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   That doesn&apos;t appear to be a valid pso2_bin directory.
        ///If you installed the game using default settings, it will probably be in C:\\PHANTASYSTARONLINE2\pso2_bin\.
        ///Otherwise, find the location you installed to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Noexe {
            get {
                return ResourceManager.GetString("Noexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse needs a valid PSO2 installation to function.
        ///The application will now close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Noinstall {
            get {
                return ResourceManager.GetString("Noinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No logs recorded in this session. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoLogs {
            get {
                return ResourceManager.GetString("NoLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Logs Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Window Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResizeWindow {
            get {
                return ResourceManager.GetString("ResizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round JA/Crit Percents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoundJA {
            get {
                return ResourceManager.GetString("RoundJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select your pso2_bin directory. OverParse uses this to read your damage logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Selectbin {
            get {
                return ResourceManager.GetString("Selectbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select your pso2_bin directory. OverParse uses this to read your damage logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Selectbox {
            get {
                return ResourceManager.GetString("Selectbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damage Separation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Separate {
            get {
                return ResourceManager.GetString("Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate A.I.S. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateAIS {
            get {
                return ResourceManager.GetString("SeparateAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate Dark Blast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateDB {
            get {
                return ResourceManager.GetString("SeparateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate HTF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateHTF {
            get {
                return ResourceManager.GetString("SeparateHTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate Laconium Sword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateLsw {
            get {
                return ResourceManager.GetString("SeparateLsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate Photon Weapons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparatePwp {
            get {
                return ResourceManager.GetString("SeparatePwp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate Rideroid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateRide {
            get {
                return ResourceManager.GetString("SeparateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separate Zanverse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparateZanverse {
            get {
                return ResourceManager.GetString("SeparateZanverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session Logs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SessionLog {
            get {
                return ResourceManager.GetString("SessionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Damage Graph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip DLL Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Skipdll {
            get {
                return ResourceManager.GetString("Skipdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clickthrough Toggle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThroughClick {
            get {
                return ResourceManager.GetString("ThroughClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide All Other Players に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThroughOther {
            get {
                return ResourceManager.GetString("ThroughOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Encounter Timeout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Log to Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToClip {
            get {
                return ResourceManager.GetString("ToClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update skills.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updatecsv {
            get {
                return ResourceManager.GetString("Updatecsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show UI Updated Time(Debug) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attack Mode Separation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VSeparate {
            get {
                return ResourceManager.GetString("VSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WinOp {
            get {
                return ResourceManager.GetString("WinOp", resourceCulture);
            }
        }
    }
}
